target-version = "py311"

[lint]
select = [
  "A",
  "ANN",
  "ARG",
  "B",
  "C4",
  "COM",
  "D",
  "E",
  "F",
  "FA",
  "FLY",
  "FURB",
  "I",
  "ISC",
  "N",
  "PERF",
  "PIE",
  "PL",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "TCH",
  "TRY",
  "UP",
  "W",
]
ignore = [
  "ANN101",
  "ANN102",
  "ANN401",
  "D100",
  "D104",
  "D203",
  "D212",
  "S311",
  "PLR0913",
  "PLR0915",
  "PLR0912",
  "S101",
  "PLW0603",
  "S104",
  "N812"
]
